{
 "title": "App Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Component Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mysql Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PHP-FPM Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phpfpm_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "App metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Nginx Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}