- name: Download node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: ['--strip-components=1', '--show-stored-names']
    mode: '755'

- name: Create node exporter user
  user:
    name: node-exporter
    shell: /bin/false
    system: true

- name: Set up node exporter service
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
  notify:
    - Start node exporter
    