global:
  scrape_interval: 5s
  external_labels:
    site: prod
remote_write:
  - url: http://127.0.0.1:8428/api/v1/write
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
rule_files:
  - /etc/prometheus/rules.yml
scrape_configs:
  - job_name: 'prometheus_master'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'airsonic-node-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.130.0.28:9100']
  - job_name: 'airsonic-nginx-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.130.0.28:9113']
  - job_name: 'airsonic-postgres-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.130.0.28:9187']
  - job_name: 'airsonic-ssl-certs-metrics'
    metrics_path: /probe
    static_configs:
      - targets:
          - airsonic.eliriand.ru:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9219
  - job_name: 'airsonic-blackbox-metrics'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://airsonic.eliriand.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
