- name: Download blackbox exporter
  unarchive:
    src: https://github.com/prometheus/blackbox_exporter/releases/download/v0.25.0/blackbox_exporter-0.25.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: ['--strip-components=1', '--show-stored-names']
    mode: '755'

- name: Create blackbox exporter user
  user:
    name: blackbox-exporter
    shell: /bin/false
    system: true

- name: Set up blackbox exporter service
  template:
    src: blackbox-exporter.service.j2
    dest: /etc/systemd/system/blackbox-exporter.service
  notify:
    - Start blackbox exporter
