---
- name: Create alertmanager system user
  user:
    name: alertmanager
    shell: /bin/false
    system: true

- name: Download alertmanager package
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.28.0/alertmanager-0.28.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: ['--show-stored-names', '--strip-components=1']
    mode: '755'
    owner: alertmanager
    group: alertmanager

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  loop:
    - '/etc/alertmanager'
    - '/etc/alertmanager/data'

- name: Render config file
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '600'
  notify:
    - Start alertmanager service

- name: Set up node alertmanager service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - Start alertmanager service